trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'MPN Subscription - Kishor Kumar M (a3a318e9-0d22-45a7-8c52-e7a4ae518271)'
  webAppName: 'sample-php'
  packagePath: '$(Build.ArtifactStagingDirectory)/app.zip'

stages:
- stage: Build
  displayName: 'Build PHP App'
  jobs:
  - job: Build
    steps:
    - checkout: self

    - task: ArchiveFiles@2
      displayName: 'Archive PHP App'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(packagePath)
        replaceExistingArchive: true
        filePatterns: |
          **/*.php
          **/*.sql

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)
        ArtifactName: 'drop'

- stage: Deploy
  displayName: 'Deploy to Azure App Service'
  dependsOn: Build
  jobs:
  - job: Deploy
    steps:
    - download: current
      artifact: drop

    - task: AzureWebApp@1
      displayName: 'Deploy App'
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(webAppName)
        package: "$(Pipeline.Workspace)/drop/app.zip"





