trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'MPN Subscription - Kishor Kumar M (a3a318e9-0d22-45a7-8c52-e7a4ae518271)'
  webAppName: 'test-php-web'
  packagePath: '$(Build.ArtifactStagingDirectory)/app.zip'

stages:

# ---------------------- BUILD ----------------------
- stage: Build
  displayName: 'Build PHP App'
  jobs:
  - job: Build
    steps:
    - checkout: self

    # Zip ONLY the files inside /app folder (no nested folder)
    - task: ArchiveFiles@2
      displayName: 'Archive PHP Application'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/app'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(packagePath)'
        replaceExistingArchive: true
        filePatterns: |
          *.php

    - task: PublishBuildArtifacts@1
      displayName: 'Publish build artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'


# ---------------------- DEPLOY ----------------------
- stage: Deploy
  displayName: 'Deploy to Azure App Service'
  dependsOn: Build
  jobs:
  - job: Deploy
    steps:
    - download: current
      artifact: 'drop'

    - task: AzureWebApp@1
      displayName: 'Deploy to App Service'
      inputs:
        azureSubscription: '$(azureSubscription)'
        appName: '$(webAppName)'
        package: '$(Pipeline.Workspace)/drop/app.zip'
        deploymentMethod: 'zipDeploy'







